[functions]
  external_node_modules = ["express"]  # Include express module in the serverless function bundle
  node_bundler = "esbuild"
 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true