[build]
  functions = "netlify/functions"  # Corrected closing quote
  publish = "dist"  # Adjust based on your build output folder

[functions]
  external_node_modules = ["express"]  # Include express module in the serverless function bundle
  node_bundler = "esbuild"  # Use esbuild for faster bundling

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  force = true